name: Deploy Lambda Function

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - src/NET8/**

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkoutRepo
          uses: actions/checkout@v2  
        - name: Build and Deploy
          uses: ./.github/actions/sam-build-and-deploy
          with:            
            aws-region: "ap-south-1"
            dotnet-version: '8.x'
            template-file-path: ./src/NET8/template.yaml
            stack-name: net-8-base
            s3-bucket-name: aws-dotnet-lambda-testing
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for Lambda function
        run: zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:ap-south-1:539659138309:function:AWSLambdaPractice01 \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"