name: Deploy .NET 8 Lambda to AWS

on:
  push:
    branches: [ main ]  # change if you deploy from another branch

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    env:
      FUNCTION_NAME: MyDotNetLambdaFunction
      RUNTIME: dotnet8
      REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Amazon Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Lambda package
      run: dotnet publish -c Release -f net8.0 -r linux-x64 -p:PublishReadyToRun=true --self-contained false -o publish

    - name: Zip published output
      run: |
        cd publish
        zip -r ../lambda-package.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name arn:aws:lambda:ap-south-1:539659138309:function:AWSLambdaPractice01 \
          --zip-file fileb://lambda-package.zip
